### ISSUE TITLE
internal logic Fail 

### ISSUE THREAD

**Issue by Jay24004** [Skelmis/Discord-Anti-Spam#99]
**Describe the bug**
internal logic Fail when trying Custom Punishments

**traceback**

Ignoring exception in on_message
Traceback (most recent call last):
  File "E:\Code\Embeder\.venv\lib\site-packages\discord\client.py", line 384, in _run_event
    await coro(*args, **kwargs)
  File "e:\Code\Embeder\cogs\automod.py", line 27, in on_message
    await self.bot.handler.propagate(message)
  File "E:\Code\Embeder\.venv\lib\site-packages\antispam\anti_spam_handler.py", line 71, in wrapper
    return await func(*args, **kwargs)
  File "E:\Code\Embeder\.venv\lib\site-packages\antispam\anti_spam_handler.py", line 328, in propagate
    after_invoke_return = await after_invoke_ext.propagate(message, main_return)
  File "E:\Code\Embeder\.venv\lib\site-packages\antispam\plugins\admin_logs.py", line 101, in propagate
    raise LogicError
antispam.exceptions.LogicError: Raised because internal logic has failed. Please create an issue in the github and include traceback.

**Screenshots**
![image](https://user-images.githubusercontent.com/79038529/159722192-c8482ef2-2705-437c-9be8-197e8381341c.png)

**Enviroment(please complete the following information):**
 - OS: Windows 10
 - Package Version: Discord-Anti-Spam  1.2.11

**Comment by Skelmis** [comment]
![Screenshot_2022-03-24-09-16-45-63_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/47520067/159788015-51bb0b4b-eb18-41db-8242-cd330a31c4d8.jpg)

Looks like custom punishments aren't supported I'd either subclass class and just copy paste things plus set the punishment type yourself or yea. Ive got an idea for changes to resolve this, it will just take a tad.

**Comment by Jay24004** [comment]
Ok
